### ISSUE TITLE
Unable to patch udma mode using python in windows 11

### ISSUE THREAD

**Issue by catogtp** [gaasedelen/titan#1]
Receive the following error when running the command: 

python tpatch.py m8plus_16_kernel.img --udma 5

[*] Patching with Titan v1.0 -- by Markus Gaasedelen
Traceback (most recent call last):
  File "N:\XBOX\titan_win32\tpatch.py", line 277, in <module>
    result = main(len(sys.argv), sys.argv)
  File "N:\XBOX\titan_win32\tpatch.py", line 266, in main
    patcher = TitanPatcher(udma=args.udma)
  File "N:\XBOX\titan_win32\tpatch.py", line 26, in __init__
    assert 2 <= udma <= 5, f"Invalid UDMA mode ({udma})"
TypeError: '<=' not supported between instances of 'int' and 'str'

Seems to need a str to int conversion on the command line args so the compare will work.

My environment is win 11 via command prompt or powershell. 
Python version output:
python --version
Python 3.9.10

**Comment by catogtp** [comment]
submitted pull request with code changes

**Comment by gaasedelen** [comment]
Good catch, fixed by #3
