### ISSUE TITLE
Is the Titan BIOS compatible with...

### ISSUE THREAD

**Issue by kaosengr** [gaasedelen/titan#15]
a currently formatted Xbox hard drive?

Do you have to reformat the hard drive to use the Titan BIOS or is it backwards compatible to support extended partition(s) already present on the hard drive formatted by XBPartitioner v1.3 with 64KB clusters.

Edit: I want to enable udma5 support but still use the current F and G partitions on a 2TB hard drive.  Or, even F and G on a 1TB hard drive, or F alone on a 1TB hard drive.

**Comment by gaasedelen** [comment]
There's nothing special about Titan's disk format, but the BIOS computes the length of the F partition based on the physical size of the disk. Scene tools and BIOS' do the same, but would clamp at `0xFFFFFFFF` sectors in the event of a larger disk.

So technically Titan *should* be compatible with drives formatted using old scene tools under the following conditions:

* The HDD *must* use standard retail partition sizes & clusters for the first 5 partitions
* The HDD *must* be formatted with 'F takes all' / 'F takes the rest of the HDD' for the 6th partition
    * This means that Titan does NOT support F & G schemes or drives
* The HDD *must* report its drive size as less than 2199023255040 bytes (2.2tb, or `0xFFFFFFFF` sectors)
    * I assume most/all 2TB drives should be well under this? If you're using a 1TB drive you should certainly be fine.

Using a 3TB drive formatted with 'F takes all' will not work under Titan. It might boot, but files will be missing or start getting corrupted on the F partition. A 1-2TB drive should be fine though.

**Comment by gaasedelen** [comment]
UDMA5 is a single byte patch to the Kernel though. If that's all you're after, I'm not sure it really makes sense to use Titan just for the faster speeds.

It should be 'pretty easy' to patch basically any Scene BIOS to use UDMA5 if you're feeling up for a little adventure!

https://github.com/gaasedelen/titan/blob/22d6b707e0cc1c3ceb82778e06721ede14afd833/tpatch.py#L89-L99

**Comment by kaosengr** [comment]
Thanks for the answers.
