### ISSUE TITLE
Critical bug with F partition size calculation

### ISSUE THREAD

**Issue by EatonZ** [gaasedelen/titan#6]
Hi - FATXplorer dev here. I was testing Titan support in FATXplorer with a user and ran into a perplexing issue where files/folders added using FATXplorer would not show up on the Xbox. Conversely, files added via a file manager on the Xbox wouldn't show in FATXplorer.

From my experience this is almost always a problem where the partition size is being calculated incorrectly. After reviewing your patches I believe I have located the issue.

The problem lies [here](https://github.com/gaasedelen/titan/blob/7d6dd70557da9b68b8f482cb077af38784975780/titan/patches/m8.py#L284). You are calculating the size of the F partition **without subtracting the starting offset of the partition (0x1DD156000)**. As a result, you are creating a partition that goes beyond the end of the disk by ~8 GB.

To verify this, I modified FATXplorer to use the disk size as the F partition size, instead of DiskSize - 0x1DD156000. After doing so, the user's files load correctly.

Fixing and not fixing this bug each has its own problems and will require careful consideration.

-If you fix it, all existing users' F partitions will suddenly break and will need reformatting. The point of these patches is to add large storage, so this could be very inconvenient to users with large amounts of data already on F.

-If you do not fix it, users will see a partition that is 8 GB larger than it actually is, and will run into problems if they actually get into that space. I also believe Matt's [FATX](https://github.com/mborgerson/fatx) project will need updating to "properly" format and mount.

**Comment by gaasedelen** [comment]
Thanks for the heads up, and good catch!

I think it's worth fixing this for the longer term, there's no reason we should have Titan partitions incompatible with 'expected' (and obviously intended) behavior. I'll submit a PR to the FATX repo too.

I can't imagine there's many people using Titan, but these types of experimental works don't come without some growing pains.

**Comment by EatonZ** [comment]
@gaasedelen I also agree that correcting it now is best, especially in the early days of the project.

If you fix the issue in the patches then I think the FATX repo's code will become correct and not need changing.

**Comment by gaasedelen** [comment]
The above commit 'should' fix this issue but I'll try to test it later tonight along with your cluster check changes.

I was hoping to include some EVTool patches in the next Titan 'release' to make it play nice, but I've been too busy with work lately to play with any Xbox stuff.

**Comment by EatonZ** [comment]
Sounds good. I can send you a test version of FATXplorer if it would help verify the fix. Email me (address on profile) or message me on reddit if you want the link.

**Comment by Supah736** [comment]
> The above commit 'should' fix this issue but I'll try to test it later tonight along with your cluster check changes.
> 
> I was hoping to include some EVTool patches in the next Titan 'release' to make it play nice, but I've been too busy with work lately to play with any Xbox stuff.

Hey if you need someone to test out the new bios feel free to ask me. I got 1 v1.4 with titan awaiting the new unbugged bios lol.

**Comment by Supah736** [comment]
Can I ask why you are taking so long on a fix some people have your bios awaiting terabytes of data?

**Comment by Supah736** [comment]
More people have your bios than not your priorties were set when you said I doubt many people are running this bios not true. Lots of people run this bios with the intent to use more modern drives and just hack around so please let's get a fix for this.

**Comment by Supah736** [comment]
It's your ethical responsibility to release a relatively quick and speedy fix as a programmer.

**Comment by EatonZ** [comment]
@Supah736 I don't think anyone outside of this issue knows about the problem, and while it will be a breaking change, it does not hinder use of the current BIOS version much.

I find your comments a bit rude because @gaasedelen has done excellent work here and open-sourced everything, for free. He's stated he is busy with work and that is always going to be a priority over a free, open-source project. After 15+ years of waiting for a 2 TB+ breakthrough, I think you can wait a little longer.

In the releases section there is a version for Windows. I have updated the latest release package and inserted the updated files. Compile with Python using [the instructions](https://github.com/gaasedelen/titan#usage) and you you should be set. Please note this remains untested. Feedback on whether it works for you or not would be appreciated.

[titan_win32_1.1.0_pre.zip](https://github.com/gaasedelen/titan/files/8402836/titan_win32_1.1.0_pre.zip)

**Comment by Supah736** [comment]
> @Supah736 I don't think anyone outside of this issue knows about the problem, and while it will be a breaking change, it does not hinder use of the current BIOS version much.
> 
> I find your comments a bit rude because @gaasedelen has done excellent work here and open-sourced everything, for free. He's stated he is busy with work and that is always going to be a priority over a free, open-source project. After 15+ years of waiting for a 2 TB+ breakthrough, I think you can wait a little longer.
> 
> In the releases section there is a version for Windows. I have updated the latest release package and inserted the updated files. Compile with Python using [the instructions](https://github.com/gaasedelen/titan#usage) and you you should be set. Please note this remains untested. Feedback on whether it works for you or not would be appreciated.
> 
> [titan_win32_1.1.0_pre.zip](https://github.com/gaasedelen/titan/files/8402836/titan_win32_1.1.0_pre.zip)

understood.

**Comment by gaasedelen** [comment]
@Supah736 It's true, my time can be spread pretty thin and I'm just poking at this stuff for fun. The alternative is I just don't publish any other Xbox research going forward so I don't have to maintain anything :-P

@EatonZ I've tested the patches (both cluster sizes and partition length fixes) on hardware and they seem good to me. I copied a full game (Halo 2) from PC to the F drive with Matt's FATX lib, and they showed up/booted fine on Xbox. I also ripped an additional game from DVD to the HDD on Xbox and was able to pull them back out on PC with FATX. 

I authored a new release ([v1.1.0](https://github.com/gaasedelen/titan/releases/tag/v1.1.0)) which yes, is 'incompatible' with drives currently formatted to use Titan. This means that people should almost certainly re-format the drive or you might experience some 'weirdness' if you chose to update your Titan-enabled BIOS to v1.1.0

As Eaton said, the benefit of this change is more to ensure that Titan is functioning how most FATX formatting tools would expect it to. Actually causing data corruption would have been 'unlikely' unless you literally filled your Titan partition to the brim. But that's why there's a whole [disclaimer](https://github.com/gaasedelen/titan#disclaimer) attached to this project ;-).

**Comment by EatonZ** [comment]
@gaasedelen Supah736 confirmed to me over email that the pre-release I posted above works correctly as well, which is basically the same as what you just released.

To clarify, the only "weirdness" that will occur is that the F drive will show no contents. The other partitions will be OK, but it will indeed be necessary to reformat to get the F drive set up properly.

**Comment by TheTimeWalker** [comment]
Hey, just as a heads-up. I found time for myself to upgrade the BIOS to v1.1.0 with the pre-release compiled build by @EatonZ. Thank you for making my life easier with it :)

I can also confirm that this worked fine on my end. As has been mentioned, with the new BIOS, the F drive would show up as empty on file managers. C and E are not hit by this and the Xbox still boots to the dashboard. Regardless, I have reformatted the drive and copied the files back, and now it's working fine. Thank you for the work and the quick fix!

**Comment by Supah736** [comment]
> Hey, just as a heads-up. I found time for myself yesterday to upgrade the BIOS to v1.1.0 with the pre-release compiled build by @EatonZ. Thank you for making my life easier with it before the official release :)
> 
> I can also confirm that this worked fine on my end. As has been mentioned, with the new BIOS, the F drive would show up as empty on file managers. C and E are not hit by this and the Xbox still boots to the dashboard. Regardless, I have reformatted the drive and copied the files back, and now it's working fine. Thank you for the work and the quick fix!

Yea but does xbmc4xbox file manager work cause it doesn't for me?

**Comment by TheTimeWalker** [comment]
I haven't noticed anything wrong with the file manager for xbmc4xbox, DVD2XBOX copying my original discs and FTP for copying my backup back

**Comment by Supah736** [comment]
> > I can also confirm that this worked fine on my end. As has been mentioned, with the new BIOS, the F drive would show up as empty on file managers. C and E are not hit by this and the Xbox still boots to the dashboard. Regardless, I have reformatted the drive and copied the files back, and now it's working fine. Thank you for the work and the quick fix!

You must have a lucky dvd drive.
